// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_MDIbD64KnmUmHf3WsR2__nvG5WA6qmY',
    appId: '1:374641794443:web:85ec6ad6ab12ec916c238e',
    messagingSenderId: '374641794443',
    projectId: 'myjourney-6a6f6',
    authDomain: 'myjourney-6a6f6.firebaseapp.com',
    storageBucket: 'myjourney-6a6f6.appspot.com',
    measurementId: 'G-PQ2DLSX485',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAimpY-sMmfAK3jc18fDDEYy_49i1fdGCA',
    appId: '1:374641794443:android:e5a6592536a67e086c238e',
    messagingSenderId: '374641794443',
    projectId: 'myjourney-6a6f6',
    storageBucket: 'myjourney-6a6f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKkyNzdkjZ_RuRDUF5gMdTTegqQD8Umwo',
    appId: '1:374641794443:ios:ae94151261660d136c238e',
    messagingSenderId: '374641794443',
    projectId: 'myjourney-6a6f6',
    storageBucket: 'myjourney-6a6f6.appspot.com',
    iosBundleId: 'com.example.myjourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKkyNzdkjZ_RuRDUF5gMdTTegqQD8Umwo',
    appId: '1:374641794443:ios:ae94151261660d136c238e',
    messagingSenderId: '374641794443',
    projectId: 'myjourney-6a6f6',
    storageBucket: 'myjourney-6a6f6.appspot.com',
    iosBundleId: 'com.example.myjourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_MDIbD64KnmUmHf3WsR2__nvG5WA6qmY',
    appId: '1:374641794443:web:3c088a634493d9936c238e',
    messagingSenderId: '374641794443',
    projectId: 'myjourney-6a6f6',
    authDomain: 'myjourney-6a6f6.firebaseapp.com',
    storageBucket: 'myjourney-6a6f6.appspot.com',
    measurementId: 'G-63N06QFVDH',
  );
}
